version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    reviewers:
      - jocgir
      - dblanchette
      - jheilcoveo
