version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    reviewers: &reviewers
      - dblanchette
      - dlevesque-coveo
      - dotboris
      - jocgir
      - jonapich
      - pballandras
      - wtrep

  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: daily
    reviewers: *reviewers
