# Build customization
version: 2
builds:
  - binary: terragrunt
    ldflags: -s -w -X main.VERSION={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

# Build one binary for Mac OS (arm64 and amd64)
universal_binaries:
  - replace: true

# Archive customization
archives:
  - format: zip
    files:
      - nothing.*

# GitHub release customization
release:
  prerelease: auto

git:
  tag_sort: -version:creatordate
  prerelease_suffix: "-"
  ignore_tags:
    - download_test
