// Code generated by "stringer -type=VariableSource -output generated_variable_source.go"; DO NOT EDIT.

package options

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndefinedSource-0]
	_ = x[Default-1]
	_ = x[ConfigVarFile-2]
	_ = x[VarFile-3]
	_ = x[VarFileExplicit-4]
	_ = x[VarParameter-5]
	_ = x[Environment-6]
	_ = x[VarParameterExplicit-7]
	_ = x[FunctionOverwrite-8]
}

const _VariableSource_name = "UndefinedSourceDefaultConfigVarFileVarFileVarFileExplicitVarParameterEnvironmentVarParameterExplicitFunctionOverwrite"

var _VariableSource_index = [...]uint8{0, 15, 22, 35, 42, 57, 69, 80, 100, 117}

func (i VariableSource) String() string {
	if i >= VariableSource(len(_VariableSource_index)-1) {
		return "VariableSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VariableSource_name[_VariableSource_index[i]:_VariableSource_index[i+1]]
}
