// Code generated by "stringer -type=SetVariableResult -output generated_set_variables.go"; DO NOT EDIT.

package options

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IgnoredVariable-0]
	_ = x[NewVariable-1]
	_ = x[Overwritten-2]
	_ = x[SetVariableResultCount-3]
}

const _SetVariableResult_name = "IgnoredVariableNewVariableOverwrittenSetVariableResultCount"

var _SetVariableResult_index = [...]uint8{0, 15, 26, 37, 59}

func (i SetVariableResult) String() string {
	if i >= SetVariableResult(len(_SetVariableResult_index)-1) {
		return "SetVariableResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SetVariableResult_name[_SetVariableResult_index[i]:_SetVariableResult_index[i+1]]
}
