// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// TerraformExtraArgumentsList represents an array of TerraformExtraArguments
type TerraformExtraArgumentsList []*TerraformExtraArguments

func (list TerraformExtraArgumentsList) init(config *TerragruntConfigFile) {
	list.toGeneric().init(config)
}

func (list *TerraformExtraArgumentsList) merge(imported TerraformExtraArgumentsList, mode mergeMode, argName string) {
	*list = toTerraformExtraArgumentsList(merge(list.toGeneric(), imported.toGeneric(), mode, argName))
}

func (list TerraformExtraArgumentsList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func toTerraformExtraArgumentsList(list []terragruntExtensioner) TerraformExtraArgumentsList {
	return convert(list, TerraformExtraArgumentsList{}).(TerraformExtraArgumentsList)
}

// Help returns the information relative to the elements within the list
func (list TerraformExtraArgumentsList) Help(listOnly bool, lookups ...string) string {
	return help(list.Enabled(), listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list TerraformExtraArgumentsList) Enabled() TerraformExtraArgumentsList {
	return toTerraformExtraArgumentsList(list.toGeneric(extensionEnabled))
}
