// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// ApprovalConfigList represents an array of ApprovalConfig
type ApprovalConfigList []*ApprovalConfig

func (list ApprovalConfigList) init(config *TerragruntConfigFile) { list.toGeneric().init(config) }

func (list *ApprovalConfigList) merge(imported ApprovalConfigList, mode mergeMode, argName string) {
	*list = toApprovalConfigList(merge(list.toGeneric(), imported.toGeneric(), mode, argName))
}

func (list ApprovalConfigList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func toApprovalConfigList(list []terragruntExtensioner) ApprovalConfigList {
	return convert(list, ApprovalConfigList{}).(ApprovalConfigList)
}

// Help returns the information relative to the elements within the list
func (list ApprovalConfigList) Help(listOnly bool, lookups ...string) string {
	return help(list.Enabled(), listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list ApprovalConfigList) Enabled() ApprovalConfigList {
	return toApprovalConfigList(list.toGeneric(extensionEnabled))
}
