// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// HookList represents an array of Hook
type HookList []*Hook

func (list HookList) init(config *TerragruntConfigFile) { list.toGeneric().init(config) }

func (list *HookList) merge(imported HookList, mode mergeMode, argName string) {
	*list = toHookList(merge(list.toGeneric(), imported.toGeneric(), mode, argName))
}

func (list HookList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func toHookList(list []terragruntExtensioner) HookList {
	return convert(list, HookList{}).(HookList)
}

// Help returns the information relative to the elements within the list
func (list HookList) Help(listOnly bool, lookups ...string) string {
	return help(list.Enabled(), listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list HookList) Enabled() HookList {
	return toHookList(list.toGeneric(extensionEnabled))
}
