// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// ImportFilesList represents an array of ImportFiles
type ImportFilesList []*ImportFiles

func (list ImportFilesList) init(config *TerragruntConfigFile) { list.toGeneric().init(config) }

func (list *ImportFilesList) merge(imported ImportFilesList, mode mergeMode, argName string) {
	*list = toImportFilesList(merge(list.toGeneric(), imported.toGeneric(), mode, argName))
}

func (list ImportFilesList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func toImportFilesList(list []terragruntExtensioner) ImportFilesList {
	return convert(list, ImportFilesList{}).(ImportFilesList)
}

// Help returns the information relative to the elements within the list
func (list ImportFilesList) Help(listOnly bool, lookups ...string) string {
	return help(list.Enabled(), listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list ImportFilesList) Enabled() ImportFilesList {
	return toImportFilesList(list.toGeneric(extensionEnabled))
}
