// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

//lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// PostHookList represents an array of PostHook
type PostHookList []*PostHook

func (list PostHookList) init(config *TerragruntConfigFile) error {
	return list.toGeneric().init(config)
}

func (list PostHookList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func (list *PostHookList) merge(data extensionList) {
	*list = toPostHookList(merge(list.toGeneric(), data, list.mergeMode()))
}

func toPostHookList(list []terragruntExtensioner) PostHookList {
	converted := convert(list, PostHookList{}).(PostHookList)
	return converted
}

func (item PostHook) itemType() string {
	return PostHookList{}.argName()
}

// Help returns the information relative to the elements within the list
func (list PostHookList) Help(listOnly bool, lookups ...string) string {
	enabled := list.Enabled()
	return help(&enabled, listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list PostHookList) Enabled() PostHookList {
	return toPostHookList(list.toGeneric(extensionEnabled))
}

// Filter is used to filter the list on supplied criteria
func (list PostHookList) Filter(filter PostHookFilter) PostHookList {
	result := make(PostHookList, 0, len(list))
	for _, item := range list.Enabled() {
		if filter(item) {
			result = append(result, item)
		}
	}
	return result
}

// PostHookFilter describe a function able to filter PostHook from a list
type PostHookFilter func(*PostHook) bool
