// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// ExtraCommandList represents an array of ExtraCommand
type ExtraCommandList []*ExtraCommand

func (list ExtraCommandList) init(config *TerragruntConfigFile) { list.toGeneric().init(config) }

func (list *ExtraCommandList) merge(imported ExtraCommandList, mode mergeMode, argName string) {
	*list = toExtraCommandList(merge(list.toGeneric(), imported.toGeneric(), mode, argName))
}

func (list ExtraCommandList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func toExtraCommandList(list []terragruntExtensioner) ExtraCommandList {
	return convert(list, ExtraCommandList{}).(ExtraCommandList)
}

// Help returns the information relative to the elements within the list
func (list ExtraCommandList) Help(listOnly bool, lookups ...string) string {
	return help(list.Enabled(), listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list ExtraCommandList) Enabled() ExtraCommandList {
	return toExtraCommandList(list.toGeneric(extensionEnabled))
}
