// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

//lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// RunConditionList represents an array of RunCondition
type RunConditionList []*RunCondition

func (list RunConditionList) init(config *TerragruntConfigFile) error {
	return list.toGeneric().init(config)
}

func (list RunConditionList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func (list *RunConditionList) merge(data extensionList) {
	*list = toRunConditionList(merge(list.toGeneric(), data, list.mergeMode()))
}

func toRunConditionList(list []terragruntExtensioner) RunConditionList {
	converted := convert(list, RunConditionList{}).(RunConditionList)
	return converted
}

func (item RunCondition) itemType() string {
	return RunConditionList{}.argName()
}

// Help returns the information relative to the elements within the list
func (list RunConditionList) Help(listOnly bool, lookups ...string) string {
	enabled := list.Enabled()
	return help(&enabled, listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list RunConditionList) Enabled() RunConditionList {
	return toRunConditionList(list.toGeneric(extensionEnabled))
}

// Filter is used to filter the list on supplied criteria
func (list RunConditionList) Filter(filter RunConditionFilter) RunConditionList {
	result := make(RunConditionList, 0, len(list))
	for _, item := range list.Enabled() {
		if filter(item) {
			result = append(result, item)
		}
	}
	return result
}

// RunConditionFilter describe a function able to filter RunCondition from a list
type RunConditionFilter func(*RunCondition) bool
