// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

//lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// ExportConfigList represents an array of ExportConfig
type ExportConfigList []*ExportConfig

func (list ExportConfigList) init(config *TerragruntConfigFile) error {
	return list.toGeneric().init(config)
}

func (list ExportConfigList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func (list *ExportConfigList) merge(data extensionList) {
	*list = toExportConfigList(merge(list.toGeneric(), data, list.mergeMode()))
}

func toExportConfigList(list []terragruntExtensioner) ExportConfigList {
	converted := convert(list, ExportConfigList{}).(ExportConfigList)
	return converted
}

func (item ExportConfig) itemType() string {
	return ExportConfigList{}.argName()
}

// Help returns the information relative to the elements within the list
func (list ExportConfigList) Help(listOnly bool, lookups ...string) string {
	enabled := list.Enabled()
	return help(&enabled, listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list ExportConfigList) Enabled() ExportConfigList {
	return toExportConfigList(list.toGeneric(extensionEnabled))
}

// Filter is used to filter the list on supplied criteria
func (list ExportConfigList) Filter(filter ExportConfigFilter) ExportConfigList {
	result := make(ExportConfigList, 0, len(list))
	for _, item := range list.Enabled() {
		if filter(item) {
			result = append(result, item)
		}
	}
	return result
}

// ExportConfigFilter describe a function able to filter ExportConfig from a list
type ExportConfigFilter func(*ExportConfig) bool
