// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

//lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// PreHookList represents an array of PreHook
type PreHookList []*PreHook

func (list PreHookList) init(config *TerragruntConfigFile) error {
	return list.toGeneric().init(config)
}

func (list PreHookList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func (list *PreHookList) merge(data extensionList) {
	*list = toPreHookList(merge(list.toGeneric(), data, list.mergeMode()))
}

func toPreHookList(list []terragruntExtensioner) PreHookList {
	converted := convert(list, PreHookList{}).(PreHookList)
	return converted
}

func (item PreHook) itemType() string {
	return PreHookList{}.argName()
}

// Help returns the information relative to the elements within the list
func (list PreHookList) Help(listOnly bool, lookups ...string) string {
	enabled := list.Enabled()
	return help(&enabled, listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list PreHookList) Enabled() PreHookList {
	return toPreHookList(list.toGeneric(extensionEnabled))
}

// Filter is used to filter the list on supplied criteria
func (list PreHookList) Filter(filter PreHookFilter) PreHookList {
	result := make(PreHookList, 0, len(list))
	for _, item := range list.Enabled() {
		if filter(item) {
			result = append(result, item)
		}
	}
	return result
}

// PreHookFilter describe a function able to filter PreHook from a list
type PreHookFilter func(*PreHook) bool
