// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

//lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// ExportVariablesList represents an array of ExportVariables
type ExportVariablesList []*ExportVariables

func (list ExportVariablesList) init(config *TerragruntConfigFile) error {
	return list.toGeneric().init(config)
}

func (list ExportVariablesList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func (list *ExportVariablesList) merge(data extensionList) {
	*list = toExportVariablesList(merge(list.toGeneric(), data, list.mergeMode()))
}

func toExportVariablesList(list []terragruntExtensioner) ExportVariablesList {
	converted := convert(list, ExportVariablesList{}).(ExportVariablesList)
	return converted
}

func (item ExportVariables) itemType() string {
	return ExportVariablesList{}.argName()
}

// Help returns the information relative to the elements within the list
func (list ExportVariablesList) Help(listOnly bool, lookups ...string) string {
	enabled := list.Enabled()
	return help(&enabled, listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list ExportVariablesList) Enabled() ExportVariablesList {
	return toExportVariablesList(list.toGeneric(extensionEnabled))
}

// Filter is used to filter the list on supplied criteria
func (list ExportVariablesList) Filter(filter ExportVariablesFilter) ExportVariablesList {
	result := make(ExportVariablesList, 0, len(list))
	for _, item := range list.Enabled() {
		if filter(item) {
			result = append(result, item)
		}
	}
	return result
}

// ExportVariablesFilter describe a function able to filter ExportVariables from a list
type ExportVariablesFilter func(*ExportVariables) bool
