// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// lint:file-ignore U1000 Ignore all unused code, it's generated

package config

// ImportVariablesList represents an array of ImportVariables
type ImportVariablesList []*ImportVariables

func (list ImportVariablesList) init(config *TerragruntConfigFile) { list.toGeneric().init(config) }

func (list *ImportVariablesList) merge(imported ImportVariablesList, mode mergeMode, argName string) {
	*list = toImportVariablesList(merge(list.toGeneric(), imported.toGeneric(), mode, argName))
}

func (list ImportVariablesList) toGeneric(filters ...extensionFilter) extensionList {
	return filterExtensions(list, filters)
}

func toImportVariablesList(list []terragruntExtensioner) ImportVariablesList {
	return convert(list, ImportVariablesList{}).(ImportVariablesList)
}

// Help returns the information relative to the elements within the list
func (list ImportVariablesList) Help(listOnly bool, lookups ...string) string {
	return help(list.Enabled(), listOnly, lookups...)
}

// Enabled returns only the enabled items on the list
func (list ImportVariablesList) Enabled() ImportVariablesList {
	return toImportVariablesList(list.toGeneric(extensionEnabled))
}
