name: Tag
on:
  push:
    tags:
      - "*"
permissions:
  contents: read

jobs:
  build:
    name: Build
    permissions:
      id-token: write # required for AWS assume role
      # This is because the permission block is replacive instead of additive so setting
      # id-token removes any other permissions the job has and goreleaser need to write contents
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: ["1.9.7"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          # We need the whole history so that goreleaser can figure out the changes
          fetch-depth: 0

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${{ matrix.terraform }}/terraform_${{ matrix.terraform }}_linux_amd64.zip -O /tmp/terraform.zip
          sudo unzip -o -d /usr/local/bin/ /tmp/terraform.zip

      - uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::043612128888:role/nrd-oss-terragrunt-github-actions-ci

      - name: Run full tests on releases
        env:
          AWS_REGION: us-east-1
        run: |
          make full-test

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
